/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latex;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author newac
 */
public class sections extends javax.swing.JFrame {

    /**
     * Creates new form sections
     */
    String filename= "output.tex";
    FileWriter fw;
    String code = "";
    
    public void openfile() {
         try {
            //the true will append the new data
            fw = new FileWriter(filename, true);

        } catch (IOException ioe) {
            System.err.println("IOException: " + ioe.getMessage());
        }
    }

    public sections() {
        initComponents();
        openfile();
        contentTF.setEnabled(false);
    }

    sections(String code) {
        initComponents();
        this.code = code;
        try
{
     //the true will append the new data
    fw = new FileWriter(filename,true);
    
}
catch(IOException ioe)
{
    System.err.println("IOException: " + ioe.getMessage());
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTF = new javax.swing.JTextField();
        addItems = new javax.swing.JButton();
        addCode = new javax.swing.JButton();
        addSubSection = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTF = new javax.swing.JTextArea();
        newSection = new javax.swing.JButton();
        addTitle = new javax.swing.JButton();
        addBody = new javax.swing.JButton();
        generatePDF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(titleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 290, 40));

        addItems.setBorderPainted(false);
        addItems.setContentAreaFilled(false);
        addItems.setFocusPainted(false);
        addItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemsActionPerformed(evt);
            }
        });
        getContentPane().add(addItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 635, 120, 130));

        addCode.setBorderPainted(false);
        addCode.setContentAreaFilled(false);
        addCode.setFocusPainted(false);
        addCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCodeActionPerformed(evt);
            }
        });
        getContentPane().add(addCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 635, 110, 130));

        addSubSection.setBorderPainted(false);
        addSubSection.setContentAreaFilled(false);
        addSubSection.setFocusPainted(false);
        addSubSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubSectionActionPerformed(evt);
            }
        });
        getContentPane().add(addSubSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 140, 130));

        contentTF.setColumns(20);
        contentTF.setRows(5);
        jScrollPane1.setViewportView(contentTF);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 450, 600, 130));

        newSection.setBorderPainted(false);
        newSection.setContentAreaFilled(false);
        newSection.setFocusPainted(false);
        newSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSectionActionPerformed(evt);
            }
        });
        getContentPane().add(newSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 785, 240, 60));

        addTitle.setIcon(new javax.swing.ImageIcon("C:\\Users\\newac\\Downloads\\check (1).png")); // NOI18N
        addTitle.setBorderPainted(false);
        addTitle.setContentAreaFilled(false);
        addTitle.setFocusPainted(false);
        addTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTitleActionPerformed(evt);
            }
        });
        getContentPane().add(addTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        addBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latex/check (1).png"))); // NOI18N
        addBody.setBorderPainted(false);
        addBody.setContentAreaFilled(false);
        addBody.setFocusPainted(false);
        addBody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBodyActionPerformed(evt);
            }
        });
        getContentPane().add(addBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, -1, -1));

        generatePDF.setBorderPainted(false);
        generatePDF.setContentAreaFilled(false);
        generatePDF.setFocusPainted(false);
        generatePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePDFActionPerformed(evt);
            }
        });
        getContentPane().add(generatePDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 860, 420, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latex/WhatsApp Image 2021-12-23 at 10.43.59 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemsActionPerformed
        try {
            new items().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(sections.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addItemsActionPerformed

    private void newSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSectionActionPerformed
        titleTF.setText("");
        contentTF.setText("");
        titleTF.setEditable(true);
        titleTF.setEnabled(true);
    }//GEN-LAST:event_newSectionActionPerformed

    private void addTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTitleActionPerformed
        try {
            //code += '\n' + "\\section{" + titleTF.getText() +  "}";
            openfile();
            fw.write('\n' + "\\section{" + titleTF.getText() +  "}");
            fw.close();
            contentTF.setEnabled(true);
            contentTF.setEditable(true);
            titleTF.setEditable(false);
            titleTF.setEnabled(false);
        } catch (IOException ex) {
            Logger.getLogger(sections.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addTitleActionPerformed

    private void addBodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBodyActionPerformed
        try {
            //code += '\n' + contentTF.getText();
            openfile();
            fw.write('\n' + contentTF.getText());
            fw.close();
            contentTF.setEditable(false);
            contentTF.setEnabled(false);
        } catch (IOException ex) {
            Logger.getLogger(sections.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBodyActionPerformed

    private void generatePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePDFActionPerformed
        try {
            //code += " \n" + "\\end{document}";
            openfile();
            fw.write(" \n" + "\\end{document}");
            fw.close();
            JOptionPane.showMessageDialog(this, "output.tex file generated");
            this.setVisible(false);
            new home().setVisible(true);
            
        } catch (IOException ex) {
            Logger.getLogger(sections.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*System.out.println(code);
        PrintWriter writer = null;
        try {
            writer = new PrintWriter("file1.tex", "UTF-8");
            writer.println(code);
            writer.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_generatePDFActionPerformed

    private void addSubSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubSectionActionPerformed
        new subsection().setVisible(true);
    }//GEN-LAST:event_addSubSectionActionPerformed

    private void addCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCodeActionPerformed
        new code().setVisible(true);
    }//GEN-LAST:event_addCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sections().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBody;
    private javax.swing.JButton addCode;
    private javax.swing.JButton addItems;
    private javax.swing.JButton addSubSection;
    private javax.swing.JButton addTitle;
    private javax.swing.JTextArea contentTF;
    private javax.swing.JButton generatePDF;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newSection;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
